### ISSUE TITLE
Sqreen clipping rack POST header RACK_REQUEST_FORM_HASH

### ISSUE THREAD

**Issue by wilkosz** [sqreen/ruby-agent#4]
## Issue 
Our `POST` requests with `content-type: multipart/form-data`, with binary file information (I imagine anything with content length > 1048396) are being clipped to `1048396 bytes`. 

## Investigation
Inspecting rack gem's `Rack::Request#POST` the `get_header(RACK_REQUEST_FORM_HASH)` appears to be modified which downstream sets the `params` method in `rails`. 

## Affected Versions
all

## Steps to reproduce 
1. using any rails application (we are currently 6.0.3.4) generate post request containing `content-type: multipart/form-data` with a binary file that is greater than `1048396 bytes`. 
2. Inspect file sizes of `get_header(RACK_REQUEST_FORM_HASH)` within `Rack::Request#POST` - this is interesting as using breakpoints will not reproduce the error instead you need to log i.e. 
```ruby
def POST
        if get_header(RACK_INPUT).nil?
          raise "Missing rack.input"
        elsif get_header(RACK_REQUEST_FORM_INPUT) == get_header(RACK_INPUT)
          get_header(RACK_REQUEST_FORM_HASH)
        elsif form_data? || parseable_data?
          # binding.pry
          unless set_header(RACK_REQUEST_FORM_HASH, parse_multipart)
            form_vars = get_header(RACK_INPUT).read

            # Fix for Safari Ajax postings that always append \0
            # form_vars.sub!(/\0\z/, '') # performance replacement:
            form_vars.slice!(-1) if form_vars.end_with?("\0")

            set_header RACK_REQUEST_FORM_VARS, form_vars
            set_header RACK_REQUEST_FORM_HASH, parse_query(form_vars, '&')

            get_header(RACK_INPUT).rewind
          end
          puts "\n>>>>>>>>>>>>#{RACK_REQUEST_FORM_HASH}\n"
          puts get_header(RACK_REQUEST_FORM_HASH)
          puts "\n>>>>>>>>>>>>>>>>>>>>\n"
          set_header RACK_REQUEST_FORM_INPUT, get_header(RACK_INPUT)
          r = get_header(RACK_REQUEST_FORM_HASH)
          puts "\n\n\nRACK POST>>>>>>>>>>>>>\n#{r&.dig('file',:tempfile)&.size}\n>>>>>>>>>>>>>>>\n\n\n" if r&.dig('file',:tempfile)&.size
          # binding.pry if r&.dig('file',:tempfile)&.size&. < 1048397
          r
        else
          {}
        end
      end
```
## Sqreen Dependencies 
runtime: ruby 2.7.1 (also used 2.7.2)
rails: 6.0.3.4 (also used 6.0.2.x through to 6.0.3.4 through to 6-0-stable branch)
```
  sqreen (1.20.4)
    libsqreen (~> 0.6.1.0.0)
    sq_mini_racer (~> 0.2.4.sqreen2)
    sqreen-backport (~> 0.1.0)
    sqreen-kit (~> 0.2.2)
```

## Logging
appears this file is called before issue occurs
`/Users/joshuawilkosz/.rvm/gems/ruby-2.7.1/gems/sqreen-1.22.0/lib/sqreen/graft/hook.rb:257: warning: Using the last argument as keyword parameters is deprecated`

**Comment by wilkosz** [comment]
workaround for anyone interested
`application_controller.rb` 
```ruby
  def params
    rtn = super
    # Sqreen clips request headers -> get_header(RACK_REQUEST_FORM_HASH)
    # i.e. request.get_header('rack.request.form_hash') and
    # request.get_header('rack.request.form_input')
    return rtn unless request.method == "POST" && 
      request.content_type == "multipart/form-data" &&
      (request.content_length&. >= 1000000) &&
      defined?(Sqreen)
    begin
      pr = request.send(:parse_multipart)
      rtn = ActionDispatch::Request::Utils.normalize_encode_params(pr)
    rescue => e
      e.notice_error
    end
    rtn
  end
```

**Comment by lloeki** [comment]
Thanks @wilkosz for this detailed report.

We appear to have identified a very likely cause for the issue and since it's not located in agent code but in our dynamic security rules, we rolled the feature back.

Would you be able to see if the issue persists? (the change is live, you don't need to redeploy)

**Comment by wilkosz** [comment]
> Thanks @wilkosz for this detailed report.
> 
> We appear to have identified a very likely cause for the issue and since it's not located in agent code but in our dynamic security rules, we rolled the feature back.
> 
> Would you be able to see if the issue persists? (the change is live, you don't need to redeploy)

Thanks, @lloeki, tested, looks good and thanks for the quick rollout!
